//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominator.Windows10.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Application {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Application() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dominator.Windows10.Localization.Application", typeof(Application).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string L_N_A {
            get {
                return ResourceManager.GetString("L_N_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO!.
        /// </summary>
        internal static string L_NO_ {
            get {
                return ResourceManager.GetString("L_NO_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        internal static string L_YES {
            get {
                return ResourceManager.GetString("L_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No support for command lines arguments yet!.
        /// </summary>
        internal static string M_No_support_for_command_lines_arguments_yet_ {
            get {
                return ResourceManager.GetString("M_No_support_for_command_lines_arguments_yet_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, {0} must be run as Administrator..
        /// </summary>
        internal static string M_Sorry___0__must_be_run_as_Administrator_ {
            get {
                return ResourceManager.GetString("M_Sorry___0__must_be_run_as_Administrator_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, {0} crashed, please open an issue at
        ///
        ///{1}
        ///
        ///Error Information:
        ///
        ///{2}.
        /// </summary>
        internal static string M_Sorry___0_crashed {
            get {
                return ResourceManager.GetString("M_Sorry___0_crashed", resourceCulture);
            }
        }
    }
}
