//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominator.Windows10.Settings.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Settings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Settings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dominator.Windows10.Settings.Localization.Settings", typeof(Settings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow apps and services to request your location.
        /// </summary>
        internal static string E_Allow_apps_and_services_to_request_your_location {
            get {
                return ResourceManager.GetString("E_Allow_apps_and_services_to_request_your_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow this PC to connect to Microsoft telemetry servers.
        /// </summary>
        internal static string E_Allow_this_PC_to_connect_to_Microsoft_telemetry_servers {
            get {
                return ResourceManager.GetString("E_Allow_this_PC_to_connect_to_Microsoft_telemetry_servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask for feedback.
        /// </summary>
        internal static string E_Ask_for_feedback {
            get {
                return ResourceManager.GetString("E_Ask_for_feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect telemetry data.
        /// </summary>
        internal static string E_Collect_telemetry_data {
            get {
                return ResourceManager.GetString("E_Collect_telemetry_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get updates from or send updates to other PCs.
        /// </summary>
        internal static string E_Get_updates_from_or_send_updates_to_other_PCs {
            get {
                return ResourceManager.GetString("E_Get_updates_from_or_send_updates_to_other_PCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let apps use my advertising ID.
        /// </summary>
        internal static string E_Let_apps_use_my_advertising_ID {
            get {
                return ResourceManager.GetString("E_Let_apps_use_my_advertising_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let websites provide locally relevant content by accessing my language list.
        /// </summary>
        internal static string E_Let_websites_provide_locally_relevant_content_by_accessing_my_language_list {
            get {
                return ResourceManager.GetString("E_Let_websites_provide_locally_relevant_content_by_accessing_my_language_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log keystrokes (WAP Push Message Routing Service).
        /// </summary>
        internal static string E_Log_keystrokes {
            get {
                return ResourceManager.GetString("E_Log_keystrokes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage all privacy related settings in one place.
        /// </summary>
        internal static string E_Manage_all_privacy_related_settings_in_one_place {
            get {
                return ResourceManager.GetString("E_Manage_all_privacy_related_settings_in_one_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft telemetry data collection.
        /// </summary>
        internal static string E_Microsoft_telemetry_data_collection {
            get {
                return ResourceManager.GetString("E_Microsoft_telemetry_data_collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide web results when I use the Windows search bar.
        /// </summary>
        internal static string E_Provide_web_results_when_I_use_the_Windows_search_bar {
            get {
                return ResourceManager.GetString("E_Provide_web_results_when_I_use_the_Windows_search_bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send data about functional issues to Microsoft (Diagnostics Tracking Service).
        /// </summary>
        internal static string E_Send_data_about_functional_issues_to_Microsoft {
            get {
                return ResourceManager.GetString("E_Send_data_about_functional_issues_to_Microsoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Microsoft info about how I write.
        /// </summary>
        internal static string E_Send_Microsoft_info_about_how_I_write {
            get {
                return ResourceManager.GetString("E_Send_Microsoft_info_about_how_I_write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings that may cause annoying consequences.
        /// </summary>
        internal static string E_Settings_that_may_cause_annoying_consequences {
            get {
                return ResourceManager.GetString("E_Settings_that_may_cause_annoying_consequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings that protect your privacy.
        /// </summary>
        internal static string E_Settings_that_protect_your_privacy {
            get {
                return ResourceManager.GetString("E_Settings_that_protect_your_privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Skype home and advertisements.
        /// </summary>
        internal static string E_Show_Skype_home_and_advertisements {
            get {
                return ResourceManager.GetString("E_Show_Skype_home_and_advertisements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of them are actually useful.
        /// </summary>
        internal static string E_Some_of_them_are_actually_useful {
            get {
                return ResourceManager.GetString("E_Some_of_them_are_actually_useful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on SmartScreen Filter to check web content (URLs) that Windows Store apps use.
        /// </summary>
        internal static string E_Turn_on_SmartScreen_Filter_to_check_web_content__URLs__that_Windows_Store_apps_use {
            get {
                return ResourceManager.GetString("E_Turn_on_SmartScreen_Filter_to_check_web_content__URLs__that_Windows_Store_apps_" +
                        "use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No support for command lines arguments yet!.
        /// </summary>
        internal static string M_No_support_for_command_lines_arguments_yet_ {
            get {
                return ResourceManager.GetString("M_No_support_for_command_lines_arguments_yet_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option not found. Evil defaults may apply..
        /// </summary>
        internal static string M_Option_not_found__Evil_defaults_may_apply {
            get {
                return ResourceManager.GetString("M_Option_not_found__Evil_defaults_may_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option value is {0} and probably safe to change..
        /// </summary>
        internal static string M_Option_value_is__0__and_probably_safe_to_change {
            get {
                return ResourceManager.GetString("M_Option_value_is__0__and_probably_safe_to_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is not installed..
        /// </summary>
        internal static string M_Service_is_not_installed {
            get {
                return ResourceManager.GetString("M_Service_is_not_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service status is not recognized, but safe to change..
        /// </summary>
        internal static string M_Service_status_is_not_recognized__but_safe_to_change {
            get {
                return ResourceManager.GetString("M_Service_status_is_not_recognized__but_safe_to_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annoyances.
        /// </summary>
        internal static string T_Annoyances {
            get {
                return ResourceManager.GetString("T_Annoyances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string T_Location {
            get {
                return ResourceManager.GetString("T_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional Protections.
        /// </summary>
        internal static string T_Optional_Protections {
            get {
                return ResourceManager.GetString("T_Optional_Protections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        internal static string T_Privacy {
            get {
                return ResourceManager.GetString("T_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telemetry.
        /// </summary>
        internal static string T_Telemetry {
            get {
                return ResourceManager.GetString("T_Telemetry", resourceCulture);
            }
        }
    }
}
